baseURL = "https://harshitpurwar.com/"
relativeURLs = true
languageCode = "en-us"
title = "Harshit Purwar: UX Engineer, Design System, CSS, HTML5, JS"


MetaDataFormat = "yaml"
SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true
disqusShortname = "harshitpurwar"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "UX"
  facebook = ""
  twitter = "https://twitter.com/harshitpurwar"
  instagram = ""


